#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# fluxbox dir
fdir="$HOME/.fluxbox"

# Kill already running process
_ps=(xsettingsd ksuperkey)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Lauch xsettingsd daemon
xsettingsd --config="$fdir"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
hsetroot -cover "$fdir"/backgrounds/default.jpg

# Lauch notification daemon
"$fdir"/scripts/fbox_dunst

# Lauch polybar
#"$fdir"/scripts/fbox_bar

# Lauch compositor
"$fdir"/scripts/fbox_comp

# Start mpd
exec mpd &

# Set your keybord layout here
#setxkbmap us -variant intl & 	# to have a us keyboard with special characters enabled (like éóíáú)

# Start Fluxbox
exec fluxbox -no-slit -log ~/.fluxbox/log
